spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: druid
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: yzm@2021
